"""add page customization models

Revision ID: 0a063fe41356
Revises: 20250611_create_refresh_tokens_table
Create Date: 2025-06-09 15:12:28.855898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a063fe41356'
down_revision: Union[str, None] = '20250611_create_refresh_tokens_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_memories_embedding_ivfflat'), postgresql_with={'lists': '100'}, postgresql_using='ivfflat')

    with op.batch_alter_table('ai_agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('queued', 'running', 'paused', 'succeeded', 'failed', name='agentstatus'), server_default='queued', nullable=False))

    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.alter_column('usage_mode',
               existing_type=postgresql.ENUM('step', 'tool', 'step_and_tool', 'function', name='nodeusagemode'),
               type_=sa.Enum('step', 'tool', 'step_and_tool', 'function', name='usagemode'),
               existing_nullable=False,
               existing_server_default=sa.text("'step'::nodeusagemode"))

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_id'))

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.alter_column('usage_mode',
               existing_type=sa.Enum('step', 'tool', 'step_and_tool', 'function', name='usagemode'),
               type_=postgresql.ENUM('step', 'tool', 'step_and_tool', 'function', name='nodeusagemode'),
               existing_nullable=False,
               existing_server_default=sa.text("'step'::nodeusagemode"))

    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('ai_agents', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('agent_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_memories_embedding_ivfflat'), ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')

    # ### end Alembic commands ###
