"""add inputs/outputs/error to flow_executions

Revision ID: 45adf8e91082
Revises: fd47950c8afc
Create Date: 2025-04-25 21:40:44.372879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45adf8e91082'
down_revision: Union[str, None] = 'fd47950c8afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flow_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('output', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('error', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flow_executions', schema=None) as batch_op:
        batch_op.drop_column('error')
        batch_op.drop_column('output')
        batch_op.drop_column('input')

    # ### end Alembic commands ###
