"""Add flow_executions table

Revision ID: 63ed37021165
Revises: 61f3fa7a806b
Create Date: 2025-04-17 16:38:37.385136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ed37021165'
down_revision: Union[str, None] = '61f3fa7a806b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_executions',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('flow_spec', sa.JSON(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('execution_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flow_executions')
    # ### end Alembic commands ###
