"""Add config JSONB to credentials

Revision ID: 710d17d69a75
Revises: f2b58d5dd57c
Create Date: 2025-04-22 18:04:01.093575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '710d17d69a75'
down_revision: Union[str, None] = 'f2b58d5dd57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('client_id')
        batch_op.drop_column('client_secret')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_secret', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('config')

    # ### end Alembic commands ###
