"""action y  Parameter

Revision ID: 89a56da1fd4b
Revises: 913ff9d48a06
Create Date: 2025-04-23 19:42:05.199910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a56da1fd4b'
down_revision: Union[str, None] = '913ff9d48a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parameters', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('required')

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
