"""Añade columna is activate

Revision ID: b52257b189ef
Revises: 45adf8e91082
Create Date: 2025-05-21 09:13:12.292798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b52257b189ef'
down_revision: Union[str, None] = '45adf8e91082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadatas', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_index('ix_agent_memories_embedding', postgresql_using='hnsw')
        batch_op.drop_column('metadata')

    with op.batch_alter_table('ai_agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('default_prompt',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('tools',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
        batch_op.alter_column('memory_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)

    with op.batch_alter_table('flow_executions', schema=None) as batch_op:
        batch_op.alter_column('flow_spec',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
        batch_op.alter_column('inputs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('outputs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
       # batch_op.drop_index('idx_flow_exec_completed')
        #batch_op.drop_index('idx_flow_exec_started')
        #batch_op.drop_index('idx_flow_exec_status')

    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('flow_executions', schema=None) as batch_op:
        batch_op.create_index('idx_flow_exec_status', ['status'], unique=False)
        batch_op.create_index('idx_flow_exec_started', ['started_at'], unique=False)
        batch_op.create_index('idx_flow_exec_completed', ['ended_at'], unique=False)
        batch_op.alter_column('outputs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('inputs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('flow_spec',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)

    with op.batch_alter_table('ai_agents', schema=None) as batch_op:
        batch_op.alter_column('memory_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('tools',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
        batch_op.alter_column('default_prompt',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('agent_memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.create_index('ix_agent_memories_embedding', ['embedding'], unique=False, postgresql_using='hnsw')
        batch_op.drop_column('metadatas')

    # ### end Alembic commands ###
