"""ADD column trigger

Revision ID: c344ae30248d
Revises: b52257b189ef
Create Date: 2025-05-24 12:04:23.172425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c344ae30248d'
down_revision: Union[str, None] = 'b52257b189ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triggers',
    sa.Column('trigger_id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('trigger_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.action_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.flow_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trigger_id')
    )
    with op.batch_alter_table('triggers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_triggers_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_triggers_flow_id'), ['flow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_triggers_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_triggers_node_id'), ['node_id'], unique=False)

    with op.batch_alter_table('flow_executions', schema=None) as batch_op:
        batch_op.drop_index('idx_flow_exec_completed')
        batch_op.drop_index('idx_flow_exec_started')
        batch_op.drop_index('idx_flow_exec_status')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flow_executions', schema=None) as batch_op:
        batch_op.create_index('idx_flow_exec_status', ['status'], unique=False)
        batch_op.create_index('idx_flow_exec_started', ['started_at'], unique=False)
        batch_op.create_index('idx_flow_exec_completed', ['ended_at'], unique=False)

    with op.batch_alter_table('triggers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_triggers_node_id'))
        batch_op.drop_index(batch_op.f('ix_triggers_job_id'))
        batch_op.drop_index(batch_op.f('ix_triggers_flow_id'))
        batch_op.drop_index(batch_op.f('ix_triggers_action_id'))

    op.drop_table('triggers')
    # ### end Alembic commands ###
