"""add param_type and action_type enum

Revision ID: fd47950c8afc
Revises: 89a56da1fd4b
Create Date: 2025-04-24 00:08:43.289256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd47950c8afc'
down_revision: Union[str, None] = '89a56da1fd4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('param_type', sa.String(), server_default='string', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parameters', schema=None) as batch_op:
        batch_op.drop_column('param_type')

    # ### end Alembic commands ###
